# Note: remember to `git submodule update --recursive` to pull in dependencies
[default]
src='packages/mangrove-solidity/contracts'
test='packages/mangrove-solidity/foundry_test'
out='packages/mangrove-solidity/foundry_out'
libs=['packages/mangrove-solidity/foundry_lib']
remappings=['hardhat/=packages/mangrove-solidity/foundry_lib/forge-std/src','@mangrovedao/hardhat-test-solidity/=packages/mangrove-solidity/node_modules/@mangrovedao/hardhat-test-solidity/']
cache_path='packages/mangrove-solidity/foundry_cache'