name: doc

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed

env:
  NODE_ENV: test
  working-directory: packages/mangrove-solidity

jobs:
  publish-mangrove-solidity-docs:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Download doc artefact from CI run
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}      
        workflow: CI
        # ...
        workflow_conclusion: success
        branch: master
        event: push
        # ...
        name: documentation
        path: docs

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}